logging:
  level:
    org.springframework.security: DEBUG

spring:
  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    url:  jdbc:h2:mem:mydb
    username: siva
    password: siva